name: Build and test package
description: 'Build and test an npm package'
inputs:
  working-directory:  # sub-folder containing package
    description: 'Package Sub-Folder'
    required: true
  generate-types: # run generate-types indicator
    description: 'Run generate-types'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Build package
      id: build-npm-package
      uses: ./.github/workflows/actions/build-package
      with:
        working-directory: ${{ inputs.working-directory }}
        generate-types: ${{ inputs.generate-types }}

    - name: Test
      shell: bash
      run: |
        cd ${{ inputs.working-directory }}
        npm test

    - name: Check coding style
      shell: bash
      run: |
        cd ${{ inputs.working-directory }}
        npm run check-style
