type data {
	RHSnodes: [node!]!
	LHSnodes: [node!]!
	links: [link!]!
}

type link implements MooDElement{
	source: endPoint!
	target: endPoint!
	id: ID!
	size: Number! @UI(name:"Size")
	colour: Colour!
}

type node implements MooDElement{
	name: Any! @UI(default:"name")
	id: ID!
}

type endPoint implements MooDElement{
	id: ID!
}