
type data {
	rootNode: node!
	level1Relationship: [relation]!
	level1LeafRelationship: [leafRelation]!
	level2Relationship: [relation]!
	level2LeafRelationship: [leafRelation]!
	level3Relationship: [relation]!
	level3LeafRelationship: [leafRelation]!
	level4LeafRelationship: [leafRelation]!
}

type node implements MooDElement{
	key: ID!
	name: String!
}

type leafNode implements MooDElement{
	key: ID!
	name: String!
	value: Number!
}

type relation implements MooDElement{
	key: ID!
	source: node! @UI(name:"Source")
	target: node! @UI(name:"Target")
}

type leafRelation implements MooDElement{
	key: ID!
	source: node! @UI(name:"Source")
	target: leafNode! @UI(name:"Target")
}