name: Build simple example packages
on:
  push:
    paths:
      - 'Examples/D3 Meta Model/**'
      - 'Examples/Echarts Meta Model/**'
      - '!**/*.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build D3 Meta Model
        uses: ./.github/workflows/actions/build-simple-package
        with:
          working-directory: './Examples/D3\ Meta\ Model'

      - name: Build ECharts Meta Model
        uses: ./.github/workflows/actions/build-simple-package
        with:
          working-directory: './Examples/ECharts\ Meta\ Model'
