name: Run Lint on Markdown documentation
on:
  push:
    paths:
      - '**/*.md'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.16.1'

      - name: Check Documentation
        uses: DavidAnson/markdownlint-cli2-action@v15
        with:
          globs: '**/*.md'
